### ISSUE TITLE
Issue with edit_column

### ISSUE THREAD

**Issue by anupalhub** [IgnitedDatatables/Ignited-Datatables#50]
helper function i created:
function is_comm($check)
    {
        if($check)
            return 'Yes';
        else
            return 'No';
    }

Now with ignited table i code in controller:
$this->datatables
            ->select('fee_id, fee_name, fee_is_comm, fee_remarks')
            ->unset_column('fee_id')
            ->edit_column('fee_is_comm', is_comm('$1'), 'fee_is_comm')
            ->from('fee_types');

But the helper function treating the $check as string ('$1') which is actually Boolean (0|1) from database. It always return "Yes".
See the issue if we can fix it.

**Comment by arwebz** [comment]
@anupalhub in my case, I can make this works, your function changed to this
`function is_comm($check)
{
	if(intval($check) == 1) return 'Yes';
	else return 'No';
}`

and in the controller
`->edit_column('fee_is_comm', '$1', 'is_comm("fee_is_comm")')`

maybe this works too
`->edit_column('fee_is_comm', '$1', "is_comm('fee_is_comm')")`

**Comment by alhamsya** [comment]
$this->is_comm('fee_is_comm')

**Comment by n1crack** [comment]
First of all you can't address the function directly. you have to put it in quotes. In addition that the function have to be global. That means you have to define your function as a helper function. 

My first comment was working. Again put the function in quotes.
->edit_column('fee_is_comm', '$1', 'is_comm(fee_is_comm)')

it returned always true in the first functio,  because you are checking if it has a value. 
@widnyana was right, it is not a boolean. it is a string. 
probably **if($check == 'true' ) or  if($check == 1 )** would worked. 

I could have improved this library but I don't want anyone break their codes.  I have rewritten the codes and make 'Composer' compatible a while ago. You can find the library . [datatables](https://github.com/n1crack/datatables)

The cons is you can't use active records like IgnitedDatatables, you have to write your sql query. And you have to use Composer of course.

the solution that I found is [edit column example](https://github.com/n1crack/datatables-examples/blob/master/sqlite_examples/edit/ajax.php).  I think this is the best practice and it  is as simple as the code below.
```
->edit('fee_is_comm',  function($data) {
  return $this->is_comm( $data['fee_is_comm'] );
})
```
And it's been 4 years. it is still an active issue. wow 😮
